"""followers,similar

Revision ID: 10ce93c375bc
Revises: a0acf8ff07d0
Create Date: 2022-11-08 13:36:47.751851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ce93c375bc'
down_revision = 'a0acf8ff07d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_artists',
    sa.Column('referenced_artist_id', sa.Integer(), nullable=True),
    sa.Column('similar_artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referenced_artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['similar_artist_id'], ['artist.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_artists')
    # ### end Alembic commands ###
