"""empty message

Revision ID: 148622bc1c26
Revises: 81687ff0a539
Create Date: 2022-12-08 13:15:25.867920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148622bc1c26'
down_revision = '81687ff0a539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('time_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_message_time_sent'), 'direct_message', ['time_sent'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direct_message_time_sent'), table_name='direct_message')
    op.drop_table('direct_message')
    # ### end Alembic commands ###
