"""followers,similar_artists

Revision ID: 2c0b4e3591ce
Revises: 10ce93c375bc
Create Date: 2022-11-09 10:52:32.601053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0b4e3591ce'
down_revision = '10ce93c375bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_artist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('similar_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['similar_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
