"""empty message

Revision ID: 81687ff0a539
Revises: d147c11e31fb
Create Date: 2022-12-08 12:00:18.236571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81687ff0a539'
down_revision = 'd147c11e31fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('time_posted', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_request_time_posted'), 'request', ['time_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_time_posted'), table_name='request')
    op.drop_column('request', 'time_posted')
    # ### end Alembic commands ###
