"""empty message

Revision ID: 95e30b8be4b1
Revises: 9e4aab23f2c0
Create Date: 2022-11-07 10:07:32.235664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e30b8be4b1'
down_revision = '9e4aab23f2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_date', sa.DateTime(), nullable=True))
    op.drop_column('user', 'joining_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joining_date', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'join_date')
    # ### end Alembic commands ###
