"""empty message

Revision ID: 9e4aab23f2c0
Revises: a36dbd6c9ff5
Create Date: 2022-11-04 12:01:13.835759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4aab23f2c0'
down_revision = 'a36dbd6c9ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joining_date', sa.DateTime(), nullable=True))
    op.drop_column('user', 'join_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_date', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'joining_date')
    # ### end Alembic commands ###
