"""empty message

Revision ID: f006d40036ff
Revises: 80edaec13f1b
Create Date: 2022-12-08 10:41:39.345533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f006d40036ff'
down_revision = '80edaec13f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=144), nullable=True),
    sa.Column('description', sa.String(length=2056), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_category'), 'request', ['category'], unique=True)
    op.create_index(op.f('ix_request_description'), 'request', ['description'], unique=True)
    op.create_index(op.f('ix_request_subject'), 'request', ['subject'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_subject'), table_name='request')
    op.drop_index(op.f('ix_request_description'), table_name='request')
    op.drop_index(op.f('ix_request_category'), table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
